name: powergenome
channels:
  - conda-forge
  # - defaults
dependencies:
  - python>=3.10 # Remove for tox.ini & setup.py
  - pip
  - jupyterlab
  - black
  - pytest
  - pytest-cov
  - beautifulsoup4>=4.8.13
  - pyyaml
  - isort
  - pre-commit
  - conda-forge::nb_conda_kernels
  - statsmodels>=0.12.2
  - conda-forge::python-dotenv
  - conda-forge::flatten-dict
  - conda-forge::ruamel.yaml
  - conda-forge::frozendict
  - conda-forge::hypothesis[pandas]
  - numpy
  - openpyxl>=3.0
  - pandas>=2.2.0
  - duckdb>=1.3.0
  - pyarrow
  - scikit-learn
  - requests
  - xlrd

  # GIS dependencies from conda-forge
  - conda-forge::fiona
  - conda-forge::geopandas>=0.12
  - conda-forge::pyogrio
  - conda-forge::shapely
