"Test functions from financials.py"

import numpy as np
import pandas as pd
import pytest

from powergenome.eia_opendata import load_aeo_series
from powergenome.financials import (  # load_cpi_data,
    inflation_price_adjustment,
    interpolate_values,
    investment_cost_calculator,
    load_dollar_year_data,
)
from powergenome.params import SETTINGS
from powergenome.settings import Settings


@pytest.fixture
def settings():
    settings = Settings(config_path="tests/test_system/settings")
    settings["data_location"] = "tests/test_system/test_data"

    if isinstance(settings["model_year"], list):
        settings["model_year"] = settings["model_year"][0]
        settings["model_first_planning_year"] = settings["model_first_planning_year"][0]
    return settings


def test_inflate_price(settings):
    p = 10
    p2 = inflation_price_adjustment(
        p,
        2000,
        2010,
        data_location=settings["data_location"],
        table_name=settings["dollar_year_table"],
    )
    assert p2 > p


def test_inflate_price_high_year(settings):
    p = 10
    with pytest.raises(ValueError):
        inflation_price_adjustment(
            p,
            2000,
            2050,
            data_location=settings["data_location"],
            table_name=settings["dollar_year_table"],
        )

    # remove later years from saved CPI file
    # cpi = pd.read_csv(tmp_path / "cpi_data.csv")
    # first_year = cpi["year"].min()
    # last_year = cpi["year"].max()
    # cpi.loc[5:10, :].to_csv(tmp_path / "cpi_data.csv", float_format="%g")

    # p = pd.Series([1, 10])
    # p2 = inflation_price_adjustment(p, first_year, last_year)
    # assert all(p2 > p)


# def test_aeo_series():
#     series_id = "AEO.2022.REF2022.PRCE_REAL_ELEP_NA_NG_NA_NEENGL_Y13DLRPMMBTU.A"
#     df = load_aeo_series(series_id)
#     assert not df.empty


# Generated by CodiumAI


class TestInvestmentCostCalculator:
    # Tests that the function correctly calculates the investment cost with a single capex, wacc, and cap_rec_years
    def test_single_capex_wacc_cap_rec_years(self, settings):
        capex = 1000
        wacc = 0.05
        cap_rec_years = 5
        expected_result = 230.97

        result = investment_cost_calculator(capex, wacc, cap_rec_years)

        assert result == pytest.approx(expected_result, abs=0.01)

    # Tests that the function correctly calculates the investment cost with list-like capex, wacc, and cap_rec_years
    def test_list_like_capex_wacc_cap_rec_years(self):
        capex = [1000, 2000, 3000]
        wacc = [0.05, 0.06, 0.07]
        cap_rec_years = [5, 10, 15]
        expected_result = [230.97, 271.73, 329.38]

        result = investment_cost_calculator(capex, wacc, cap_rec_years)

        assert result == pytest.approx(expected_result, abs=0.01)

    # Tests that the function raises a TypeError when a single capex and wacc are provided, but list-like cap_rec_years
    def test_single_capex_wacc_list_like_cap_rec_years(self):
        capex = 1000
        wacc = 0.05
        cap_rec_years = [5, 10, 15]

        with pytest.raises(TypeError):
            investment_cost_calculator(capex, wacc, cap_rec_years)

    # Tests that the function correctly calculates the investment cost with list-like capex and cap_rec_years, but a single wacc
    def test_list_like_capex_cap_rec_years_single_wacc(self):
        capex = [1000, 2000, 3000]
        wacc = 0.05
        cap_rec_years = [5, 10, 15]
        expected_result = [230.97, 259.01, 289.03]

        result = investment_cost_calculator(capex, wacc, cap_rec_years)

        assert result == pytest.approx(expected_result, abs=0.01)

    # Tests that the function correctly calculates the investment cost with list-like capex and wacc, but a single cap_rec_years
    def test_list_like_capex_wacc_single_cap_rec_years(self):
        capex = [1000, 2000, 3000]
        wacc = [0.05, 0.06, 0.07]
        cap_rec_years = 5
        expected_result = [230.97, 474.79, 731.67]

        result = investment_cost_calculator(capex, wacc, cap_rec_years)

        assert result == pytest.approx(expected_result, abs=0.01)

    # Tests that the function correctly calculates the investment cost with list-like capex, wacc, and cap_rec_years using continuous compounding
    def test_list_like_capex_wacc_cap_rec_years_continuous_compounding(self):
        capex = [1000, 2000, 3000]
        wacc = [0.05, 0.06, 0.07]
        cap_rec_years = [5, 10, 15]
        compound_method = "continuous"
        expected_result = [231.79, 274.11, 334.62]

        result = investment_cost_calculator(capex, wacc, cap_rec_years, compound_method)

        assert result == pytest.approx(expected_result, abs=0.01)

    # Tests that a ValueError is raised when the compound_method argument is set to "neither"
    def test_invalid_compound_method(self):
        capex = [1000, 2000, 3000]
        wacc = [0.05, 0.06, 0.07]
        cap_rec_years = [5, 10, 15]
        compound_method = "neither"

        with pytest.raises(ValueError):
            investment_cost_calculator(capex, wacc, cap_rec_years, compound_method)

    # Tests that a ValueError is raised when one of the capex values is nan
    def test_nan_capex_value(self):
        capex = [1000, np.nan, 2000]
        wacc = 0.05
        cap_rec_years = 5

        with pytest.raises(ValueError):
            investment_cost_calculator(capex, wacc, cap_rec_years)

    # Tests that the function correctly calculates the investment cost with list-like capex, wacc, and cap_rec_years as pandas Series
    def test_list_like_capex_wacc_cap_rec_years_as_pandas_series(self):
        capex = pd.Series([1000, 2000, 3000])
        wacc = pd.Series([0.05, 0.06, 0.07])
        cap_rec_years = pd.Series([5, 10, 15])
        expected_result = np.array([230.97, 271.73, 329.38])

        result = investment_cost_calculator(capex, wacc, cap_rec_years)

        assert result == pytest.approx(expected_result, abs=0.01)


@pytest.fixture
def base_df():
    # Base DataFrame with two points for interpolation
    return pd.DataFrame({"year": [2000, 2010], "value": [100.0, 200.0]})


def test_interpolate_single_year(base_df):
    # Interpolate a single missing year
    result = interpolate_values(base_df, 2005)
    # Should have 3 rows now
    assert len(result) == 3
    # Check interpolated value at 2005
    interpolated = result[result["year"] == 2005]["value"].iloc[0]
    assert pytest.approx(interpolated, rel=1e-6) == 150.0
    # Check sorted order
    assert list(result["year"]) == [2000, 2005, 2010]


def test_existing_year_no_duplicate(base_df):
    # Interpolating an existing year should not duplicate it
    result = interpolate_values(base_df, 2000)
    # Still only two rows
    assert len(result) == 2
    # Values unchanged
    assert list(result["value"]) == [100.0, 200.0]


def test_multiple_years_args(base_df):
    # Pass multiple years as separate args
    result = interpolate_values(base_df, 2002, 2008)
    assert set(result["year"]) == {2000, 2002, 2008, 2010}
    # Check two interpolations
    v2002 = result[result["year"] == 2002]["value"].iloc[0]
    v2008 = result[result["year"] == 2008]["value"].iloc[0]
    assert pytest.approx(v2002, rel=1e-6) == 120.0
    assert pytest.approx(v2008, rel=1e-6) == 180.0


def test_multiple_years_list_and_args(base_df):
    # Pass a list and a scalar
    result = interpolate_values(base_df, [2003, 2007], 2009)
    assert set(result["year"]) == {2000, 2003, 2007, 2009, 2010}


def test_no_args_raises(base_df):
    with pytest.raises(ValueError):
        interpolate_values(base_df)


def test_year_out_of_range_raises_low(base_df):
    with pytest.raises(ValueError):
        interpolate_values(base_df, 1990)


def test_year_out_of_range_raises_high(base_df):
    with pytest.raises(ValueError):
        interpolate_values(base_df, 2020)


# Note: load_dollar_year_data internally does:
#     df = load_data(data_location=data_location, table_name=table_name)
# so we patch powergenome.financials.load_data.


def test_load_dollar_year_data_success(monkeypatch):
    # Simulate a valid DataFrame with the required columns
    sample_df = pd.DataFrame({"year": [2000], "value": [1.0]})
    monkeypatch.setattr(
        "powergenome.financials.load_data",
        lambda data_location, file_or_table_name: sample_df,
    )
    result = load_dollar_year_data("ignored_path", "ignored_table")
    # Should return the exact DataFrame
    assert result is sample_df


def test_load_dollar_year_data_empty(monkeypatch):
    # Simulate an empty DataFrame
    empty_df = pd.DataFrame(columns=["year", "value"])
    monkeypatch.setattr(
        "powergenome.financials.load_data",
        lambda data_location, file_or_table_name: empty_df,
    )
    with pytest.raises(ValueError) as excinfo:
        load_dollar_year_data("loc", "tbl")
    assert "empty" in str(excinfo.value).lower()


@pytest.mark.parametrize(
    "bad_df, missing_cols",
    [
        (pd.DataFrame({"value": [1.0]}), ["year"]),
        (pd.DataFrame({"year": [2000]}), ["value"]),
        (pd.DataFrame({"foo": [1], "bar": [2]}), ["year", "value"]),
    ],
)
def test_load_dollar_year_data_missing_columns(monkeypatch, bad_df, missing_cols):
    # Simulate a DataFrame missing one or both required columns
    monkeypatch.setattr(
        "powergenome.financials.load_data",
        lambda data_location, file_or_table_name: bad_df,
    )
    with pytest.raises(ValueError) as excinfo:
        load_dollar_year_data("loc", "tbl")
    msg = str(excinfo.value).lower()
    # Ensure the error mentions missing 'year' and 'value'
    for col in missing_cols:
        assert col in msg
