name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      # matrix:
      #   python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.11"
    - name: Install powergenome with dev dependencies
      run: |
        uv sync --extra dev
    - name: Lint with flake8
      run: |
        uv pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        RESOURCE_GROUPS: ${{ secrets.RESOURCE_GROUPS }}
        PUDL_DB: ${{ secrets.PUDL_DB }}
        PG_DB: ${{ secrets.PG_DB }}
      run: |
        uv run pytest --cov=powergenome tests/ --cov-report=xml
    - name: Upload test coverage report to CodeCov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
